# Build Stage
FROM golang:1.24.5-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o croplink-backend

# Final Stage
FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/croplink-backend .

EXPOSE 8080
CMD ["./croplink-backend"]  