apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: croplink
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  CLERK_SECRET_KEY: c2tfdGVzdF8xaXd1MWpaVGIyVEtZSmNjam1kdTE4TEhlZ054d1FGcWs0SWVOMWRrbHU=