apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: croplink
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: 08abhinav/croplinkbackend:latest
          name: backend-img
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config