apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: croplink
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_DBNAME: croplink
  DB_SSLMODE: disable
  BASE_URL: "http://localhost:8080"