apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-deploy
    namespace: croplink
    labels:
      app: frontend
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
          - image: 08abhinav/croplinkfrontend:latest
            name: frontend-img
            ports:
              - containerPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    name: frontend-service
    namespace: croplink
  spec:
    ports:
      - port: 80
        targetPort: 80
    selector: 
      app: frontend
kind: List
metadata: {}