name: ci

on:
  push:
    branches: ["master"]
    path-ignore:
      - "**.md"
      - 'docs/**'
      - '.gitignore'
  workflow_dispatch:

env:
  REGISTRY: 08abhinav
  IMAGE_TAG: ${{github.sha}}

jobs:
  checkout:
    name: "Checkout: ${{ matrix.services.name }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        services:
          - name: "backend"
            dir: "./backend"
            node-version: "22"

          - name: "frontend"
            dir: "./frontend"
            node-version: "22"
    defaults:
      run:
        shell: bash
        working-directory: ${{matrix.services.dir}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.services.node-version}}
      
      - name: Install dependencies
        run: npm ci
  
  security:
    name: "Gitleaks Secret Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  buld-push:
    name: "Build, Scan and Push Image"
    runs-on: ubuntu-latest
    needs: [checkout, security]
    strategy:
      matrix:
        services:
          - image_name: "croplink-backend"
            context: "./backend"
          - image_name: "croplink-frontend"
            context: "./frontend"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
          -t $${{env.REGISTRY}}/${{matrix.services.image_name}}/${{env.IMAGE_TAG}} \
          -t $${{env.REGISTRY}}/${{matrix.services.image_name}}:latest \
          ${{matrix.services.context}}
      
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{env.REGISTRY}}/${{matrix.services.image_name}}:${{env.IMAGE_TAG}}'
          format: 'table'
          exit-code: 0
      
      - name: Signin To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DockerHUB_USERNAME}}
          password: ${{secrets.DockerHUB_PASSWORD}}
      
      - name: Push Docker Image
        run: |
          docker push ${{env.REGISTRY}}/${{matrix.services.image_name}}:${{env.IMAGE_TAG}}
          docker push ${{env.REGISTRY}}/${{matrix.services.image_name}}:latest